In [3]:
import numpy as np

#create a 1-dimensional array
a1 = np.array([1,2,3])

#create a 2-dimensional array
a2 = np.array([[1,2,3],
               [4,5,6]])

#create a 3-dimensional array
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
                  [[1,2,3],
                   [4,5,6],
                   [7,8,9]],
              ])

print(a3.shape)
print(a3.dtype)
print(a3.size)

a3.ndim

(2, 3, 3)
int32
18


3

In [4]:
#create an array of only ones

ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
#create an array within a range of 0 to 100 with step 3 

arange_array = np.arange(0,100,3)

arange_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
#create a random array pf numbers between 0 to 10 of size (4,6)

np.random.seed(40)

a4 = np.random.randint(100, size=(4,6))

a4.shape
a4.size

a4.reshape(2, 12)

np.square(a4)


array([[4900, 8281,   49, 1369, 3136, 2500],
       [4225,  144, 5041,  361,  961, 5476],
       [3025, 6889, 3481, 8281, 5329, 9216],
       [2401, 2809, 5329,   64, 2704,  900]])

In [14]:
#perform a dot product calculation on  two arrays 

a1 = np.random.randint(10, size=(1,1))
a2 = np.random.randint(10, size=(1,1))   

print(a1)
print(a2)

np.dot(a1, a2)


[[8]]
[[6]]


array([[48]])